Registration
long Registration::studentId
unsigned Registration::semester
unsigned Registration::count
Result Registration::r[MaxResults][MaxResults]
Registration::Registration()
unsigned Registration::GetCredits() const
References GetCredits.
Referenced by GetCredits, main.
unsigned Registration::GetCount() const
Referenced by main.
ostream & operator<<(ostream &os, const Registration &R)
istream & operator>>(istream &input, Registration &R)